version: '3.8'

volumes:
    prometheus_data: {}
    grafana_data: {}
    mysql-1_data: {}
    mysql-2_data: {}
    mysql-3_data: {}
    alertmanager_data: {}
    federated-mysql-1_data: {}
    federated-mysql-2_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana:10.1.5
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000

  node-exporter:
    image: prom/node-exporter:v1.6.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - "9100"

  redis:
    image: redis
    expose:
      - "6379"

  redis-exporter:
    image: oliver006/redis_exporter
    command: -redis.addr redis://redis:6379
    expose:
      - "9121"

  alertmanager:
    image: prom/alertmanager:v0.26.0
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alertmanager_data:/data
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    restart: unless-stopped
    expose:
      - "9093"
  
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.24.0
    command:
      - --config.file=/etc/blackbox/blackbox.yml
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    expose:
      - "9115"

  mysql-1:
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - mysql-1_data:/var/lib/mysql
    expose:
      - "3306"
  
  mysql-2:
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - mysql-2_data:/var/lib/mysql
    expose:
      - "3306"
  
  mysql-3:
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - mysql-3_data:/var/lib/mysql
    expose:
      - "3306"

  mysql-exporter:
    command:
     - "--config.my-cnf=/mysql-exporter/.my.cnf"
    restart: unless-stopped
    image: prom/mysqld-exporter
    volumes:
      - ./mysql-exporter/.my.cnf:/mysql-exporter/.my.cnf
    depends_on:
      - mysql-1
      - mysql-2
      - mysql-3
    expose:
      - "9104"

########### FEDEREATION SECTION #############
  
  federated-prometheus-1:
    image: prom/prometheus:v2.5.0
    ports:
    - 9091:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.enable-lifecycle
    volumes:
    - ./federated-prometheus-1/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  
  federated-mysql-1:
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - federated-mysql-1_data:/var/lib/mysql
    expose:
      - "3306"

  federated-mysql-exporter-1:
    command:
     - "--config.my-cnf=/mysql-exporter/.my.cnf"
    restart: unless-stopped
    image: prom/mysqld-exporter
    volumes:
      - ./mysql-exporter/.my.cnf:/mysql-exporter/.my.cnf
    expose:
      - "9104"
    depends_on:
      - federated-mysql-1
  
  federated-prometheus-2:
    image: prom/prometheus:v2.5.0
    ports:
    - 9092:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.enable-lifecycle
    volumes:
    - ./federated-prometheus-2/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  
  federated-mysql-2:
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - federated-mysql-2_data:/var/lib/mysql
    expose:
      - "3306"

  federated-mysql-exporter-2:
    command:
     - "--config.my-cnf=/mysql-exporter/.my.cnf"
    restart: unless-stopped
    image: prom/mysqld-exporter
    volumes:
      - ./mysql-exporter/.my.cnf:/mysql-exporter/.my.cnf
    expose:
      - "9104"
    depends_on:
      - federated-mysql-2