global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: federated-prometheus-1
    static_configs:
      - targets: ["federated-prometheus-1:9090"]

  - job_name: federated-mysql-exporter-1
    static_configs:
      - targets:
        - federated-mysql-1:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: federated-mysql-exporter-1:9104
